#!/bin/sh

COMMON_PATHS="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
HOME_LOCAL_PATH="$HOME/.local/bin"
YARN_PATH="$HOME/.yarn-config/global/node_modules/.bin"

# Postgres host
export PGHOST=localhost

export GOROOT="$HOME/.local/go"
export GOPATH="$GOROOT/bin"

export RBENV_ROOT="$HOME/.rbenv"

NPM_PACKAGES="$HOME/.npm-packages/bin"
RBENV_PATH="$RBENV_ROOT/shims:$RBENV_ROOT/bin:$RBENV_ROOT/plugins/ruby-build/bin"
GAMES_PATH="/usr/games:/usr/local/games"
export PATH="$RBENV_PATH:$HOME_LOCAL_PATH:$COMMON_PATHS:$GAMES_PATH:$GOPATH:$YARN_PATH:$NPM_PACKAGES"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='subl'
fi

#GPG
GPG_TTY=$(tty)
export GPG_TTY
export NVM_DIR="$HOME/.nvm"

# Lazy load nvm
nvm() {
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
  nvm "$@"
}

. ~/.local/env
