#!/bin/sh

COMMON_PATHS="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
HOME_LOCAL_PATH="$HOME/.local/bin"
HEROKU_PATH="/usr/local/heroku/bin"
YARN_PATH="$HOME/.yarn-config/global/node_modules/.bin"

# Postgres host
export PGHOST=localhost

export GOROOT="$HOME/.local/go"
export GOPATH="$GOROOT/bin"

export RBENV_ROOT="$HOME/.rbenv"

RBENV_PATH="$RBENV_ROOT/shims:$RBENV_ROOT/bin:$RBENV_ROOT/plugins/ruby-build/bin"
GAMES_PATH="/usr/games:/usr/local/games"
export PATH="$HEROKU_PATH:$RBENV_PATH:$HOME_LOCAL_PATH:$COMMON_PATHS:$GAMES_PATH:$GOPATH:$YARN_PATH"

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
else
  export EDITOR='subl --wait'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# # ssh
# if ! pgrep -u $USER ssh-agent > /dev/null; then
#     ssh-agent > ~/.ssh-agent-thing
# fi
# if [[ "$SSH_AGENT_PID" == "" ]]; then
#     eval $(<~/.ssh-agent-thing)
# fi
# ssh-add -l >/dev/null || alias ssh='ssh-add -l >/dev/null || ssh-add && unalias ssh; ssh'

#GPG
GPG_TTY=$(tty)
export GPG_TTY
export NVM_DIR="$HOME/.nvm"

# Lazy load nvm
nvm() {
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
  nvm "$@"
}
. ~/.local/env
