---
- name: asdf - download
  become: no
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ home_dir }}/.asdf"
    version: "{{ asdf_version }}"
    update: yes
  tags: asdf

- name: asdf - plugins
  become: no
  shell: "asdf plugin-add {{ item }}"
  with_items:
    - ruby
    - elixir
    - erlang
    - direnv
    - nodejs
  tags: asdf

- name: asdf - plugins
  become: no
  shell: "asdf install {{ item }} latest"
  with_items:
    - ruby
    - elixir
    - erlang
    - direnv
    - nodejs
  tags: asdf
