---
- name: git_standup - exists
  stat: path=/usr/local/bin/git-standup
  register: git_standup
  tags: git-standup

- name: git standup - download
  become: no
  git:
    repo: https://github.com/kamranahmedse/git-standup.git
    dest: "{{ home_dir }}/code/apps/git-standup"
    update: yes
  tags: git-standup

- name: git standup - install
  become: yes
  command:
    chdir="{{ home_dir }}/code/apps/git-standup"
    make install
  tags: git-standup
  when: not git_standup.stat.exists
