---
- name: greeter - config
  template:
    src: "{{ ansible_dir }}/system/files/lightdm.conf"
    dest: /etc/lightdm/lightdm.conf
  tags: greeter

- name: greeter-theme - config
  template:
    src: "{{ ansible_dir }}/system/files/lightdm-gtk-greeter.conf"
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
  tags: greeter
