---
- name: grub - config
  lineinfile:
    dest: /etc/default/grub
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {
      regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=.*$',
      line: GRUB_CMDLINE_LINUX_DEFAULT="acpi_rev_override=1 acpi_osi=Linux nouveau.modeset=0 pcie_aspm=force drm.vblankoffdelay=1 scsi_mod.use_blk_mq=1 nouveau.runpm=0 mem_sleep_default=deep i915.i915_enable_fbc=1 mitigations=off"
    }
    - {
      regexp: '^GRUB_TIMEOUT=\d*$',
      line: GRUB_TIMEOUT=0
    }
  tags: grub

- name: grub - update
  command: update-grub
  tags: grub
