---
- name: libinput-gestures - exists
  stat: path=/usr/bin/libinput-gestures
  register: libinput-gestures

- name: libinput gestures - download
  become: no
  git:
    repo=http://github.com/bulletmark/libinput-gestures.git
    dest="{{ home_dir }}/code/apps/libinput-gestures"
    update=no

- name: libinput-gestures - install
  command:
    chdir="{{ home_dir }}/code/apps/libinput-gestures/"
    make install
  when: not libinput-gestures.stat.exists
