---
- name: Apps | Install with apt-get
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - aisleriot
    - gnome-mines
    - gnome-mahjongg
    - gnome-sudoku
    - nautilus
    - cheese
    - rhythmbox
    - totem
  tags:
    - apt
    - apt-remove
