---
- name: Apps | Install with apt-get
  tags:
    - apt
    - apt-remove
  apt:
    state: absent
    pkg:
      - aisleriot
      - gnome-mines
      - gnome-mahjongg
      - gnome-sudoku
      - nautilus
      - cheese
      - rhythmbox
      - totem
