---
- name: Updates apt cache
  apt: update_cache=true
  tags:
    - apt
    - ppa

- name: Apps | Install with apt-get
  tags: apt
  apt:
    state: latest
    pkg:
      # power management
      - acpi
      - acpi-support
      - tlp
      - tlp-rdw

      # printing
      - cups

      # usability
      # - gnome-characters
      - libinput-tools
      - redshift
      - redshift-gtk
      - xautomation
      - xdotool
      - xbindkeys
      - solaar
      - trash-cli
      - imwheel
      - unclutter

      # desktop environment
      # - blueberry
      # - cinnamon
      # - dconf-tools
      - dconf-editor
      # - nemo
      # - nemo-dropbox
      # - nemo-fileroller
      # - nemo-share
      # - python-nemo

      # development
      - hub
      - sublime-text

      # theming
      - kimmo-gtk-theme
      - qt5-style-platform-gtk2
      - qt5-style-plugin-gtk2
      - papirus-icon-theme
      - breeze-cursor-theme

      # internet
      - firefox
      - chromium-browser
      - duplicity
      - insync
      - insync-nemo
      - transmission

      # dev environment
      - python3-pip
      - nodejs
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - zeal
      - yarn

      # terminal / shell
      - git
      - httpie
      - tilix
      - tree
      - xclip
      - zsh

      # tools
      - baobab
      - curl
      - copyq
      - font-manager
      - fzf
      - gdebi
      - gnome-calculator
      - gnome-disk-utility
      - gnome-system-monitor
      - htop
      - inkscape
      - flameshot
      - jq
      - keepassxc
      - p7zip-full
      - p7zip-rar
      - ppa-purge
      - rcm

      - shellcheck
      - software-properties-gtk
      - synaptic
      - vim
      - wkhtmltopdf

      # networking
      - gufw
      - ufw

      # media
      - evince
      - gimp
      - guvcview
      - libasound2-plugin-equal
      - viewnior
      - vlc

      # dependencies
      - apt-transport-https
      - autoconf
      - build-essential
      - cmake
      - cpphs
      - dh-autoreconf
      # - libcurl4-openssl-dev
      # - libev-dev
      # - libffi-dev
      # - libgcrypt11-dev
      # - libmysqlclient-dev
      # - libpango1.0-dev
      # - libpq-dev
      # - libqt4-dev
      # - libreadline-dev
      # - libsqlite3-dev

      # for ruby:
      - libssl-dev

      # - libstartup-notification0-dev
      # - libxcb-cursor-dev
      # - libxcb-icccm4-dev
      # - libxcb-keysyms1-dev
      # - libxcb-randr0-dev
      # - libxcb-util0-dev
      # - libxcb-xinerama0-dev
      # - libxcb-xkb-dev
      # - libxcb1-dev
      # - libxkbcommon-dev
      # - libxkbcommon-x11-dev
      - libxml2-dev
      # - libxslt1-dev
      # - libyajl-dev
      # - libyaml-dev
      # - linux-image-extra-virtual
      - llvm
      - ncurses-doc
      - python3-software-properties
      - qt5-default
      - uvcdynctrl
      - wmctrl
      - xdotool
      # - zlib1g-dev
