---
- name: systemd templates
  template:
    src: "{{ ansible_dir }}/system/files/systemd/{{ item }}"
    dest: /etc/systemd/system/{{ item }}
  with_items:
    # - clock-mod-fix.service
    - dconf.service
    - dconf.timer
    - duplicity.service
    - duplicity.timer
  tags: systemd

- name: enable systemd services
  systemd:
    enabled: yes
    name: "{{ item }}"
  with_items:
    # - clock-mod-fix.service
    - dconf.service
    - duplicity.service
  tags: systemd

- name: enable systemd timers
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
    - dconf.timer
    - duplicity.timer
  tags: systemd
